"""templateCell model simplification

Revision ID: 0766bd223509
Revises: 8bcbca06c241
Create Date: 2025-06-17 12:16:07.511276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0766bd223509'
down_revision = '8bcbca06c241'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('template_cells', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_iterative', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('iteration_direction', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('data_source', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('data_field', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('custom_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('cell_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.drop_column('extra_config')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('template_cells', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extra_config', sa.TEXT(), nullable=True))
        batch_op.alter_column('cell_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('custom_text')
        batch_op.drop_column('data_field')
        batch_op.drop_column('data_source')
        batch_op.drop_column('iteration_direction')
        batch_op.drop_column('is_iterative')

    # ### end Alembic commands ###
