"""tabla de asociacion materias-grados

Revision ID: 10399e3d4711
Revises: 4329c66e0d41
Create Date: 2025-05-09 10:51:08.170041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10399e3d4711'
down_revision = '4329c66e0d41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subject_grade',
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('grade_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['grade_id'], ['grades.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('subject_id', 'grade_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subject_grade')
    # ### end Alembic commands ###
