"""Add templates things

Revision ID: 4ac10e3617ea
Revises: 55e4380229c6
Create Date: 2025-06-12 12:21:32.564596

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '4ac10e3617ea'
down_revision = '55e4380229c6'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        # CAMBIAR ESTA LÍNEA - darle un nombre a la constraint
        batch_op.create_unique_constraint('uq_teachers_employee_id', ['employee_id'])

    with op.batch_alter_table('template_cells', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_type', sa.String(length=50), nullable=True))
        batch_op.alter_column('cell_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               nullable=True)
        batch_op.alter_column('default_value',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.drop_column('content_type')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('template_cells', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_type', sa.VARCHAR(length=50), nullable=True))
        batch_op.alter_column('default_value',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('cell_type',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_column('data_type')

    with op.batch_alter_table('teachers', schema=None) as batch_op:
        # CAMBIAR ESTA LÍNEA TAMBIÉN
        batch_op.drop_constraint('uq_teachers_employee_id', type_='unique')
    # ### end Alembic commands ###
