"""template config

Revision ID: 8a4a4aca6b92
Revises: 4ac10e3617ea
Create Date: 2025-06-12 20:02:00.220297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a4a4aca6b92'
down_revision = '4ac10e3617ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('template_cells', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extra_config', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('template_cells', schema=None) as batch_op:
        batch_op.drop_column('extra_config')

    # ### end Alembic commands ###
