"""add template ranges for iterative data

Revision ID: 8bcbca06c241
Revises: 8a4a4aca6b92
Create Date: 2025-06-12 20:58:43.764516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bcbca06c241'
down_revision = '8a4a4aca6b92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('template_ranges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('range_name', sa.String(length=50), nullable=False),
    sa.Column('start_cell', sa.String(length=10), nullable=False),
    sa.Column('end_cell', sa.String(length=10), nullable=True),
    sa.Column('range_type', sa.String(length=20), nullable=False),
    sa.Column('data_mapping', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['excel_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('template_ranges')
    # ### end Alembic commands ###
