"""templateCell add "content_type" column

Revision ID: b9eedc32e6d3
Revises: d72ab7bde420
Create Date: 2025-06-19 11:44:55.062253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9eedc32e6d3'
down_revision = 'd72ab7bde420'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('template_cells', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('template_cells', schema=None) as batch_op:
        batch_op.drop_column('content_type')

    # ### end Alembic commands ###
