"""template original model

Revision ID: d72ab7bde420
Revises: 0766bd223509
Create Date: 2025-06-17 16:34:18.957674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd72ab7bde420'
down_revision = '0766bd223509'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('template_cells', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extra_config', sa.Text(), nullable=True))
        batch_op.alter_column('cell_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_column('is_iterative')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('data_source')
        batch_op.drop_column('created_at')
        batch_op.drop_column('data_field')
        batch_op.drop_column('custom_text')
        batch_op.drop_column('iteration_direction')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('template_cells', schema=None) as batch_op:
        batch_op.add_column(sa.Column('iteration_direction', sa.VARCHAR(length=10), nullable=True))
        batch_op.add_column(sa.Column('custom_text', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('data_field', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('data_source', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('is_iterative', sa.BOOLEAN(), nullable=True))
        batch_op.alter_column('cell_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.drop_column('extra_config')

    # ### end Alembic commands ###
