"""nuevas columnas para gradetypesform

Revision ID: e6c665240623
Revises: 10399e3d4711
Create Date: 2025-05-14 13:22:56.519155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6c665240623'
down_revision = '10399e3d4711'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grade_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teacher_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('section_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_grade_types_teacher_id', 'teachers', ['teacher_id'], ['id'])
        batch_op.create_foreign_key('fk_grade_types_section_id', 'sections', ['section_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grade_types', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('section_id')
        batch_op.drop_column('teacher_id')

    # ### end Alembic commands ###
